name: workflow_02

on:
  workflow_dispatch:
    inputs:
      workflow_02:
        description: 'Workflow 2 which will be triggered'
        required: true
        default: 'workflow_02'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'userName' # Remove the colons

      workflow2_repo_github:
        description: 'repo-name'
        required: true
        default: 'repoName' # Remove the colons

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow 2
        run: |
          curl -X POST "https://api.github.com/repos/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/dispatches" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -u ${{ secrets.GIT_TOKEN }} \
          --data '{"event_type": "${{ github.event.inputs.workflow_02 }}", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
        env:
          GITHUB_REPOSITORY: ${{ github.event.repository.full_name }}
      - uses: actions/checkout@v3